---
# cluster role
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "configurator.fullname" . }}
  namespace: {{ include "configurator.namespace" . }}
  labels:
    {{- include "configurator.labels" . | nindent 4 }}
rules:
  - apiGroups: [""]
    resources: ["configmap", "secrets"]
    verbs: ["get", "list", "watch", "update"]

---
# cluster role binding
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "configurator.fullname" . }}
  namespace: {{ include "configurator.namespace" . }}
  labels:
    {{- include "configurator.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "configurator.fullname" . }}
subjects:
  - kind: ServiceAccount
    name: {{ include "configurator.fullname" . }}
    namespace: {{ include "configurator.namespace" . }}

---
# service account
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "configurator.fullname" . }}
  namespace: {{ include "configurator.namespace" . }}
  labels:
    {{- include "configurator.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}