---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "configurator.fullname" . }}
  namespace: {{ include "configurator.namespace" . }}
  labels:
    {{- include "configurator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type | default "ClusterIP" }}
  ports:
    {{- range .Values.ports }}
    - port: {{ .containerPort }}
      targetPort: {{ .containerPort }}
      protocol: {{ .protocol }}
      name: {{ .name }}
    {{- end }}
  selector:
    {{- include "configurator.selectorLabels" . | nindent 4 }}