# Configuration file for development environment
cluster: <your-cluster-name>

promtail:
  local_bin: /opt/homebrew/bin/promtail
  sampling:
    selector:
      format: "{workload=\"%s\"} |= \"\""
  secret:
    name: promtail
    namespace: kube-logging
    key: promtail.yaml

metrics:
  mimir_tenant: <tenant_id>
  query_timeout: 30s

scheduling:
  timezone: Asia/Kolkata
  cron:
    budget_reset: "0 0 * * *" # every day at midnight

budget:
  config_path: ./config/budget.yaml
  org: <org_name
  env: stage
  multiplier: 1
  mimimum: 0.5

log:
  level: trace
  format: json

# only required when using mode: dev
mode: dev

kube_config: .tmp/kubeconfig

dry_run: true